from django.core.management.base import BaseCommand
from cafe.models import MenuItem
ITEMS = [{'bestseller': 1,
  'category': 'Burgers',
  'description': 'Crispy veggie burger with fresh toppings.',
  'diet': 'veg',
  'id': 'veggie',
  'image': 'veggie-burger.png',
  'name': 'Veggie',
  'price': 99},
 {'bestseller': 0,
  'category': 'Burgers',
  'description': 'Classic chicken burger with cheese.',
  'diet': 'nonveg',
  'id': 'classic-cheese-chicken',
  'image': 'classic-cheese-chicken-burger.png',
  'name': 'Classic Cheese - Chicken',
  'price': 169},
 {'bestseller': 0,
  'category': 'Burgers',
  'description': 'Classic beef burger with cheese.',
  'diet': 'nonveg',
  'id': 'classic-cheese-beef',
  'image': 'classic-cheese-beef-burger.png',
  'name': 'Classic Cheese - Beef',
  'price': 189},
 {'bestseller': 1,
  'category': 'Burgers',
  'description': 'Crispy chicken burger with signature sauce.',
  'diet': 'nonveg',
  'id': 'crispy',
  'image': 'crispy-burger.png',
  'name': 'Crispy',
  'price': 199},
 {'bestseller': 1,
  'category': 'Burgers',
  'description': 'Street Baik signature burger.',
  'diet': 'nonveg',
  'id': 'signature-burger',
  'image': 'signature-burger.png',
  'name': 'Signature',
  'price': 220},
 {'bestseller': 1,
  'category': 'Chef Special',
  'description': 'Crispy chicken with signature sauce.',
  'diet': 'nonveg',
  'id': 'dynamite-medium',
  'image': 'dynamite-chicken.png',
  'name': 'Dynamite Chicken - Medium',
  'price': 199},
 {'bestseller': 0,
  'category': 'Chef Special',
  'description': 'A larger serving of dynamite chicken.',
  'diet': 'nonveg',
  'id': 'dynamite-large',
  'image': 'dynamite-chicken.png',
  'name': 'Dynamite Chicken - Large',
  'price': 250},
 {'bestseller': 0,
  'category': 'Chef Special',
  'description': 'Street-style grilled chicken alfahm.',
  'diet': 'nonveg',
  'id': 'alfahm-quarter',
  'image': 'street-chicken-alfahm.png',
  'name': 'Street Chicken Alfahm - Quarter',
  'price': 199},
 {'bestseller': 1,
  'category': 'Chef Special',
  'description': 'Half chicken alfahm.',
  'diet': 'nonveg',
  'id': 'alfahm-half',
  'image': 'street-chicken-alfahm.png',
  'name': 'Street Chicken Alfahm - Half',
  'price': 399},
 {'bestseller': 1,
  'category': 'Chef Special',
  'description': 'Full chicken alfahm.',
  'diet': 'nonveg',
  'id': 'alfahm-full',
  'image': 'street-chicken-alfahm.png',
  'name': 'Street Chicken Alfahm - Full',
  'price': 750},
 {'bestseller': 0,
  'category': 'Chef Special',
  'description': 'Creamy Alfredo pasta.',
  'diet': 'veg',
  'id': 'pasta-alfredo',
  'image': 'alfredo-pasta.png',
  'name': 'Signature Pasta - Alfredo',
  'price': 219},
 {'bestseller': 0,
  'category': 'Chef Special',
  'description': 'Street Baik signature pasta.',
  'diet': 'nonveg',
  'id': 'pasta-signature',
  'image': 'signature-pasta.png',
  'name': 'Signature Pasta - Signature',
  'price': 270},
 {'bestseller': 1,
  'category': 'Chef Special',
  'description': 'Loaded crispy fries.',
  'diet': 'veg',
  'id': 'loaded-fries-normal',
  'image': 'loaded-fries.png',
  'name': 'Loaded Fries - Normal',
  'price': 199},
 {'bestseller': 0,
  'category': 'Chef Special',
  'description': 'Signature loaded fries.',
  'diet': 'veg',
  'id': 'loaded-fries-signature',
  'image': 'loaded-fries.png',
  'name': 'Loaded Fries - Signature',
  'price': 250},
 {'bestseller': 0,
  'category': 'Chef Special',
  'description': 'Classic street hot dog.',
  'diet': 'nonveg',
  'id': 'hot-dog-classic',
  'image': 'classic-hot-dog.png',
  'name': 'Hot Dog - Classic',
  'price': 79},
 {'bestseller': 0,
  'category': 'Chef Special',
  'description': 'Cheesy hot dog with a rich topping.',
  'diet': 'nonveg',
  'id': 'hot-dog-cheese',
  'image': 'cheese-volcano-hot-dog.png',
  'name': 'Hot Dog - Cheese Volcano',
  'price': 120},
 {'bestseller': 1,
  'category': 'Combos',
  'description': 'Tenders (2 pcs) + lemon juice.',
  'diet': 'nonveg',
  'id': 'starting-combo',
  'image': 'starting-combo.png',
  'name': 'Starting Combo',
  'price': 99},
 {'bestseller': 0,
  'category': 'Combos',
  'description': 'Crispy chicken combo.',
  'diet': 'nonveg',
  'id': 'crispy-2s',
  'image': 'crispy-2s-combo.png',
  'name': 'Crispy 2s Combo',
  'price': 179},
 {'bestseller': 0,
  'category': 'Combos',
  'description': 'Wrap with crunchy sides.',
  'diet': 'nonveg',
  'id': 'wrap-crunch',
  'image': 'wrap-and-crunch.png',
  'name': 'Wrap and Crunch',
  'price': 199},
 {'bestseller': 0,
  'category': 'Combos',
  'description': 'Crispy burger + fries.',
  'diet': 'nonveg',
  'id': 'street-solo',
  'image': 'street-solo-meal.png',
  'name': 'Street Solo Meal',
  'price': 249},
 {'bestseller': 1,
  'category': 'Combos',
  'description': 'Fried chicken, tender and soft drink.',
  'diet': 'nonveg',
  'id': 'super-combo',
  'image': 'super-combo.png',
  'name': 'Super Combo',
  'price': 289},
 {'bestseller': 0,
  'category': 'Combos',
  'description': 'Fried chicken, tenders, wrap and fries.',
  'diet': 'nonveg',
  'id': 'street-box',
  'image': 'street-box.png',
  'name': 'Street Box',
  'price': 499},
 {'bestseller': 0,
  'category': 'Combos',
  'description': 'Hot & crispy meal with sides and drink.',
  'diet': 'nonveg',
  'id': 'hot-crispy-combo',
  'image': 'hot-and-crispy.png',
  'name': 'Hot & Crispy Combo',
  'price': 599},
 {'bestseller': 0,
  'category': 'Combos',
  'description': 'Chicken melt wrap, classic cheese burger, loaded fries and more.',
  'diet': 'nonveg',
  'id': 'classic-combo-pack',
  'image': 'classic-combo-pack.png',
  'name': 'Classic Combo Pack',
  'price': 699},
 {'bestseller': 1,
  'category': 'Combos',
  'description': 'Signature alfahm, dynamite chicken, signature burger and sides.',
  'diet': 'nonveg',
  'id': 'signature-combo',
  'image': 'signature-combo.png',
  'name': 'Signature Combo',
  'price': 899},
 {'bestseller': 1,
  'category': 'Combos',
  'description': 'Family-size selection with burgers, chicken, fries and drinks.',
  'diet': 'nonveg',
  'id': 'family-combo',
  'image': 'family-combo.png',
  'name': 'Family Combo',
  'price': 999},
 {'bestseller': 0,
  'category': 'Hot & Crispy',
  'description': 'Hot and crispy fried chicken.',
  'diet': 'nonveg',
  'id': 'fried-1',
  'image': 'fried-chicken.png',
  'name': 'Fried Chicken - 1 Pc',
  'price': 99},
 {'bestseller': 0,
  'category': 'Hot & Crispy',
  'description': 'Two pieces of crispy fried chicken.',
  'diet': 'nonveg',
  'id': 'fried-2',
  'image': 'fried-chicken.png',
  'name': 'Fried Chicken - 2 Pcs',
  'price': 179},
 {'bestseller': 0,
  'category': 'Hot & Crispy',
  'description': 'Three pieces of crispy fried chicken.',
  'diet': 'nonveg',
  'id': 'fried-3',
  'image': 'fried-chicken.png',
  'name': 'Fried Chicken - 3 Pcs',
  'price': 249},
 {'bestseller': 1,
  'category': 'Hot & Crispy',
  'description': 'Four pieces of crispy fried chicken.',
  'diet': 'nonveg',
  'id': 'fried-4',
  'image': 'fried-chicken.png',
  'name': 'Fried Chicken - 4 Pcs',
  'price': 299},
 {'bestseller': 0,
  'category': 'Hot & Crispy',
  'description': 'Crispy tenders with peri peri seasoning.',
  'diet': 'nonveg',
  'id': 'tenders-eri-peri',
  'image': 'eri-peri-tenders.png',
  'name': 'Tenders - Eri Peri',
  'price': 149},
 {'bestseller': 1,
  'category': 'Hot & Crispy',
  'description': 'Crispy tenders with Korean spicy flavour.',
  'diet': 'nonveg',
  'id': 'tenders-korean',
  'image': 'korean-spicy-tenders.png',
  'name': 'Tenders - Korean Spicy',
  'price': 159},
 {'bestseller': 0,
  'category': 'Hot & Crispy',
  'description': 'Street Baik signature tenders.',
  'diet': 'nonveg',
  'id': 'tenders-signature',
  'image': 'signature-tenders.png',
  'name': 'Tenders - Signature',
  'price': 159},
 {'bestseller': 0,
  'category': 'Drinks',
  'description': 'Freshly brewed tea.',
  'diet': 'veg',
  'id': 'tea',
  'image': 'tea-chai.png',
  'name': 'Tea (Chai)',
  'price': 20},
 {'bestseller': 0,
  'category': 'Drinks',
  'description': 'Hot café-style coffee.',
  'diet': 'veg',
  'id': 'coffee',
  'image': 'coffee.png',
  'name': 'Coffee',
  'price': 25},
 {'bestseller': 0,
  'category': 'Drinks',
  'description': 'Refreshing lemon drink.',
  'diet': 'veg',
  'id': 'lemon-normal',
  'image': 'lemon-juice-normal.png',
  'name': 'Lemon - Normal',
  'price': 30},
 {'bestseller': 0,
  'category': 'Drinks',
  'description': 'Flavoured lemon cooler.',
  'diet': 'veg',
  'id': 'lemon-flavoured',
  'image': 'lemon-juice-flavoured.png',
  'name': 'Lemon - Flavoured',
  'price': 70},
 {'bestseller': 0,
  'category': 'Drinks',
  'description': 'Fresh apple juice.',
  'diet': 'veg',
  'id': 'apple-juice',
  'image': 'apple-juice.png',
  'name': 'Apple Juice',
  'price': 120},
 {'bestseller': 0,
  'category': 'Drinks',
  'description': 'Fresh watermelon juice.',
  'diet': 'veg',
  'id': 'watermelon-juice',
  'image': 'watermelon-juice.png',
  'name': 'Watermelon Juice',
  'price': 99},
 {'bestseller': 0,
  'category': 'Drinks',
  'description': 'Fresh citrus juice.',
  'diet': 'veg',
  'id': 'citrus-juice',
  'image': 'citrus-juice.png',
  'name': 'Citrus Juice',
  'price': 99},
 {'bestseller': 0,
  'category': 'Drinks',
  'description': 'Fresh orange juice.',
  'diet': 'veg',
  'id': 'orange-juice',
  'image': 'orange-juice.png',
  'name': 'Orange Juice',
  'price': 120},
 {'bestseller': 0,
  'category': 'Drinks',
  'description': 'Fresh pineapple juice.',
  'diet': 'veg',
  'id': 'pineapple-juice',
  'image': 'pineapple-juice.png',
  'name': 'Pineapple Juice',
  'price': 99},
 {'bestseller': 0,
  'category': 'Drinks',
  'description': 'Fresh mango juice.',
  'diet': 'veg',
  'id': 'mango-juice',
  'image': 'mango-juice.png',
  'name': 'Mango Juice',
  'price': 120},
 {'bestseller': 1,
  'category': 'Drinks',
  'description': 'Refreshing mojito cooler.',
  'diet': 'veg',
  'id': 'blue-curacao',
  'image': 'blu-curacao-mojito.png',
  'name': 'Blue Curacao Mojito',
  'price': 89},
 {'bestseller': 0,
  'category': 'Drinks',
  'description': 'Refreshing green apple mojito.',
  'diet': 'veg',
  'id': 'green-apple',
  'image': 'green-apple-mojito.png',
  'name': 'Green Apple Mojito',
  'price': 89},
 {'bestseller': 0,
  'category': 'Drinks',
  'description': 'Fresh kiwi mojito.',
  'diet': 'veg',
  'id': 'kiwi-mojito',
  'image': 'kiwi-mojito.png',
  'name': 'Kiwi Mojito',
  'price': 89},
 {'bestseller': 0,
  'category': 'Drinks',
  'description': 'Tropical passion fruit mojito.',
  'diet': 'veg',
  'id': 'passion-fruit',
  'image': 'passion-fruit-mojito.png',
  'name': 'Passion Fruit Mojito',
  'price': 89},
 {'bestseller': 0,
  'category': 'Drinks',
  'description': 'Berry-flavoured mojito.',
  'diet': 'veg',
  'id': 'very-berry',
  'image': 'very-berry-mojito.png',
  'name': 'Very Berry Mojito',
  'price': 89},
 {'bestseller': 0,
  'category': 'Frappes',
  'description': 'Cold blended coffee.',
  'diet': 'veg',
  'id': 'cold-coffee',
  'image': 'cold-coffee-frappe.png',
  'name': 'Cold Coffee',
  'price': 90},
 {'bestseller': 0,
  'category': 'Frappes',
  'description': 'Rich Irish-style coffee frappe.',
  'diet': 'veg',
  'id': 'irish-coffee',
  'image': 'irish-coffee-frappe.png',
  'name': 'Irish Coffee',
  'price': 130},
 {'bestseller': 0,
  'category': 'Frappes',
  'description': 'Creamy caramel frappe.',
  'diet': 'veg',
  'id': 'caramel-frappe',
  'image': 'caramel-frappe.png',
  'name': 'Caramel',
  'price': 140},
 {'bestseller': 1,
  'category': 'Frappes',
  'description': 'Rich chocolate frappe.',
  'diet': 'veg',
  'id': 'chocolate-frappe',
  'image': 'chocolate-frappe.png',
  'name': 'Chocolate',
  'price': 150},
 {'bestseller': 0,
  'category': 'Shakes',
  'description': 'Classic vanilla shake.',
  'diet': 'veg',
  'id': 'vanilla-shake',
  'image': 'vanilla-shake.png',
  'name': 'Vanilla',
  'price': 100},
 {'bestseller': 0,
  'category': 'Shakes',
  'description': 'Creamy coconut shake.',
  'diet': 'veg',
  'id': 'coco-shake',
  'image': 'coco-coconut-shake.png',
  'name': 'Coco (Coconut)',
  'price': 120},
 {'bestseller': 1,
  'category': 'Shakes',
  'description': 'Mango shake.',
  'diet': 'veg',
  'id': 'mango-shake',
  'image': 'mango-shake.png',
  'name': 'Mango',
  'price': 120},
 {'bestseller': 0,
  'category': 'Shakes',
  'description': 'Creamy avocado shake.',
  'diet': 'veg',
  'id': 'avocado-shake',
  'image': 'avocado-shake.png',
  'name': 'Avocado',
  'price': 120},
 {'bestseller': 0,
  'category': 'Shakes',
  'description': 'Oreo cookie shake.',
  'diet': 'veg',
  'id': 'oreo-shake',
  'image': 'oreo-shake.png',
  'name': 'Oreo',
  'price': 130},
 {'bestseller': 0,
  'category': 'Shakes',
  'description': 'Fun bubble gum shake.',
  'diet': 'veg',
  'id': 'bubble-gum-shake',
  'image': 'bubble-gum-shake.png',
  'name': 'Bubble Gum',
  'price': 140},
 {'bestseller': 0,
  'category': 'Shakes',
  'description': 'Popcorn-inspired shake.',
  'diet': 'veg',
  'id': 'popcorn-shake',
  'image': 'popcorn-shake.png',
  'name': 'Popcorn',
  'price': 140},
 {'bestseller': 1,
  'category': 'Shakes',
  'description': 'Creamy Lotus Biscoff shake.',
  'diet': 'veg',
  'id': 'lotus-shake',
  'image': 'lotus-biscoff-shake.png',
  'name': 'Lotus Biscoff',
  'price': 160}]
class Command(BaseCommand):
 def handle(self,*args,**kwargs):
  for x in ITEMS: MenuItem.objects.update_or_create(id=x["id"],defaults=x)
  self.stdout.write(self.style.SUCCESS(f"Seeded {len(ITEMS)} menu items."))
