from django.db import migrations, models
import django.utils.timezone
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[]
    operations=[
        migrations.CreateModel(name='MenuItem',fields=[
            ('id',models.CharField(max_length=80,primary_key=True,serialize=False)),('category',models.CharField(max_length=80)),('name',models.CharField(max_length=160)),('price',models.DecimalField(decimal_places=2,max_digits=8)),('image',models.CharField(max_length=160)),('description',models.TextField()),('diet',models.CharField(max_length=20)),('bestseller',models.BooleanField(default=False)),('active',models.BooleanField(default=True))]),
        migrations.CreateModel(name='Order',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('public_id',models.CharField(max_length=40,unique=True)),('customer_name',models.CharField(max_length=120)),('email',models.EmailField(blank=True,max_length=254)),('phone',models.CharField(max_length=20)),('address',models.TextField()),('order_type',models.CharField(max_length=20)),('table_no',models.CharField(blank=True,max_length=30)),('instructions',models.TextField(blank=True)),('latitude',models.FloatField(blank=True,null=True)),('longitude',models.FloatField(blank=True,null=True)),('subtotal',models.DecimalField(decimal_places=2,max_digits=10)),('delivery_charge',models.DecimalField(decimal_places=2,default=0,max_digits=10)),('tax',models.DecimalField(decimal_places=2,default=0,max_digits=10)),('total',models.DecimalField(decimal_places=2,max_digits=10)),('payment_method',models.CharField(max_length=60)),('payment_status',models.CharField(default='Pending',max_length=30)),('status',models.CharField(choices=[(x,x) for x in ['Pending','Confirmed','Preparing','Ready','Completed','Cancelled']],default='Pending',max_length=30)),('items_json',models.JSONField(default=list)),('created_at',models.DateTimeField(default=django.utils.timezone.now)),('updated_at',models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name='Reservation',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('booking_id',models.CharField(max_length=40,unique=True)),('name',models.CharField(max_length=120)),('phone',models.CharField(max_length=20)),('email',models.EmailField(blank=True,max_length=254)),('date',models.DateField()),('time',models.TimeField()),('guests',models.PositiveIntegerField()),('request',models.TextField(blank=True)),('status',models.CharField(choices=[('Pending','Pending'),('Approved','Approved'),('Rejected','Rejected'),('Completed','Completed')],default='Pending',max_length=20)),('created_at',models.DateTimeField(default=django.utils.timezone.now))]),
        migrations.CreateModel(name='Review',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120)),('rating',models.PositiveSmallIntegerField()),('review',models.TextField()),('status',models.CharField(choices=[('Pending','Pending'),('Approved','Approved'),('Rejected','Rejected')],default='Pending',max_length=20)),('created_at',models.DateTimeField(default=django.utils.timezone.now))]),
        migrations.CreateModel(name='Message',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120)),('email',models.EmailField(blank=True,max_length=254)),('phone',models.CharField(blank=True,max_length=20)),('message',models.TextField()),('created_at',models.DateTimeField(default=django.utils.timezone.now))]),
        migrations.CreateModel(name='NotificationLog',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('order',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='cafe.order')),('channel',models.CharField(max_length=30)),('event',models.CharField(max_length=60)),('status',models.CharField(max_length=30)),('detail',models.TextField(blank=True)),('created_at',models.DateTimeField(default=django.utils.timezone.now))]),
    ]
