# Generated by Django 5.2.17 on 2026-09-24 23:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_alter_menuitem_options_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_upload',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
